### ISSUE TITLE
Problem with escaped "

### ISSUE THREAD

**Issue by jkleiser** [TheMue/bbedit-pony#1]
Hi,

I see that your plug-in doesn't handle escaped quotes like it should. See second line from the bottom, in attached screen shot.

![bbedit](https://cloud.githubusercontent.com/assets/107986/8925716/5ff3d614-350a-11e5-93f5-f13d38470ecf.png)

**Comment by TheMue** [comment]
Thx, will take a look and fix asap.

**Comment by TheMue** [comment]
Fixed and also added docstrings highlighted as comments.
