### ISSUE TITLE
Quote in identifier' not handled properly

### ISSUE THREAD

**Issue by jkleiser** [TheMue/bbedit-pony#2]
Try this:
`new create(film': String) =>`

See attached screen clip.
![ident-quote](https://cloud.githubusercontent.com/assets/107986/10690461/5eb3adf8-7982-11e5-8fc0-4b7b117a35b0.png)

**Comment by TheMue** [comment]
Ouch, so they are allowed in identifiers? In this case I have to check how to change the language module to distinguish between the beginning of a string and a quote in an identifier.

**Comment by TheMue** [comment]
Fixed.
