### ISSUE TITLE
Quote in identifier' still not handled properly

### ISSUE THREAD

**Issue by jkleiser** [TheMue/bbedit-pony#3]
I replaced the old Pony.bbpackage in Packages with the new one, then quit BBEdit and started again, but I still see the same "error" in `new create(film': String) =>` as before. Do I have to log out and back in, don't think so.
I'm using BBEdit 11.1.3, which should be the latest version.
I can try on another Mac when I get home.

**Comment by TheMue** [comment]
Oh, that's really an interesting behavior. I'm using the 11.1.3 too and here it works.

Have to think about it. It reminds me of another trouble I once had with the parsing very long strings (in Go sources). BareBones didn't had the troubles. I reinstalled BBEdit, even removed the Application Support/BBEdit. But that didn't helped. But then I repaired it, but cannot remember how.

**Comment by jkleiser** [comment]
Now I have tried your new Pony.bbpackage on my Mac at home (it has OS X 10.10.5, while the other had 10.9.5), and I cannot see any improvement here either. I checked a different Pony file, and you can see the same old error here:
![ident-quote](https://cloud.githubusercontent.com/assets/107986/10699425/02cd1ef4-79b7-11e5-86dd-1e1d049f9a51.png)
When I did the `git pull`, I see there was only one tiny change:
```
From https://github.com/TheMue/bbedit-pony
   fc51a4e..c5993a1  master     -> origin/master
   fc51a4e..c5993a1  develop    -> origin/develop
Updating fc51a4e..c5993a1
Fast-forward
 Pony.bbpackage/Contents/Language Modules/Pony.plist | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
Is that what it should be?

**Comment by TheMue** [comment]
Yes, only one small change. I added the quote to the identifier chars. But this doesn't seem to be the solution. I'm now wondering why it works here.

**Comment by TheMue** [comment]
Solved it by not highlighting char literals ('x') anymore.
